### ISSUE TITLE
venv in version control

### ISSUE THREAD

**Issue by jdekarske** [mdekarske/Nfl_Stats#4]
Looks like your environment is still tracked after you added the .gitignore. You have the `requirements.txt` which will generate that!

I think [this](https://stackoverflow.com/questions/24290358/remove-a-folder-from-git-tracking) is a solution

**Comment by mdekarske** [comment]
Simple solution.  

1. Delete the local env file.  
2. Commit all and sync
3. Rebuild the local env file from the requirements.txt

Fixed!
